### ISSUE TITLE
Radar shows officer sprite when vieweing bodycam feed

### ISSUE THREAD

**Issue by GreveGit** [Your-Spy/spy-bodycam#1]
When a police officer is watching, be able to disable the officers blip hovering on you, when im out in the field and a officer is viewing the feed, their duty sprite shows on the map on me, so i can basicly see him watching me by using the map, doesnt feel right, maybe add it into the ui instead if this is intended or just a gta thing. highly appreciated

**Comment by Your-Spy** [comment]
hey it is because of your player ped gets teleported to the place of another officer. As one sync doesn't load players far off the map. U can make changes in ur policejob where the blips are created. U can also join discord if u require some help.
