### ISSUE TITLE
Issue with backspace not working to exit while "watch mode"

### ISSUE THREAD

**Issue by AJDAROCKSTARR** [Your-Spy/spy-bodycam#2]
Found an issue: Backspace does not work when looking through bodycam. In the first iteration the people stayed around the watch location, now they disappear and can only bring them back by stopping/restarting resource. Love the resource and I hope this helps. Let me know if there's any questions or comments.

**Comment by Your-Spy** [comment]
Is ur bodycam exit key in fivem keymapping setting different from the script. Check once

**Comment by AJDAROCKSTARR** [comment]
It was indeed. Gave it default 'E' instead of backspace. My apologies.
